obj-$(CONFIG_MACH_APQ8064_PALMAN) += board-palman.o \
	board-palman-camera.o \
	board-palman-display.o \
	board-palman-gpiomux.o \
	board-palman-gpu.o \
	board-palman-input.o	\
	board-palman-pmic.o \
	board-palman-regulator.o \
	board-palman-misc.o \
	board-palman-sound.o \
	board-palman-storage.o

CFLAGS_board-palman-display.o += -Idrivers/video
